server:
  port: 8080
spring:
  datasource:
    username: root
    password: Rjvgfc123
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true # Показ SQL запросов в консоли для отладки
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

# example values

indexing-settings:
  sites:
    - url: https://lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
  user-agent: YourSearchBot
  referrer: https://www.google.com